# TTS服务配置示例
# 复制此文件为 config.tts.yaml 并填入实际的API密钥

tts:
  # 默认配置
  default_provider: "openai"
  default_voice: "alloy"
  default_format: "mp3"
  default_speed: 1.0
  default_pitch: 1.0
  default_volume: 1.0
  
  # 存储配置
  storage:
    save_to_server: true
    audio_storage_path: "storage/audio"
    max_file_size: 10485760  # 10MB
    cleanup_after_days: 30   # 30天后清理文件
  
  # 缓存配置
  cache:
    enabled: true
    ttl: 3600  # 1小时
    max_size: 1000
  
  # 限流配置
  rate_limit:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
    requests_per_day: 10000
  
  # 提供商配置
  providers:
    openai:
      enabled: true
      api_key: "your-openai-api-key"
      base_url: "https://api.openai.com/v1"
      timeout: 30
      retry_count: 3
      max_text_length: 4096
      supported_formats: ["mp3", "opus", "aac", "flac"]
      supported_voices: ["alloy", "echo", "fable", "onyx", "nova", "shimmer"]
      price_per_character: 0.000015  # $0.015 per 1K characters
    
    baidu:
      enabled: true
      api_key: "your-baidu-api-key"
      secret_key: "your-baidu-secret-key"
      base_url: "https://tsn.baidu.com"
      timeout: 30
      retry_count: 3
      max_text_length: 1024
      supported_formats: ["mp3"]
      supported_voices: ["0", "1", "3", "4"]  # 度小美、度小宇、度逍遥、度小娇
      price_per_character: 0.00001  # 约0.01元/千字符
    
    step:
      enabled: true
      api_key: "your-step-api-key"
      base_url: "https://api.stepfun.com/v1"
      timeout: 30
      retry_count: 3
      max_text_length: 2000
      supported_formats: ["mp3", "wav"]
      supported_voices: ["cixingnansheng", "tianmeinvxing"]
      price_per_character: 0.00002
    
    minimax:
      enabled: true
      api_key: "your-minimax-api-key"
      base_url: "https://api.minimax.chat/v1"
      timeout: 30
      retry_count: 3
      max_text_length: 10000
      supported_formats: ["mp3", "wav"]
      supported_voices: ["default"]
      price_per_character: 0.000025
    
    azure:
      enabled: false
      api_key: "your-azure-api-key"
      region: "eastus"
      base_url: "https://eastus.tts.speech.microsoft.com"
      timeout: 30
      retry_count: 3
      max_text_length: 5000
      supported_formats: ["mp3", "wav", "ogg"]
      supported_voices: ["zh-CN-XiaoxiaoNeural", "zh-CN-YunxiNeural"]
      price_per_character: 0.000016
    
    google:
      enabled: false
      api_key: "your-google-api-key"
      base_url: "https://texttospeech.googleapis.com/v1"
      timeout: 30
      retry_count: 3
      max_text_length: 5000
      supported_formats: ["mp3", "wav", "ogg"]
      supported_voices: ["zh-CN-Wavenet-A", "zh-CN-Wavenet-B"]
      price_per_character: 0.000016

# 环境变量配置（可选，用于敏感信息）
# 在 .env 文件中设置：
# OPENAI_API_KEY=your-openai-api-key
# BAIDU_API_KEY=your-baidu-api-key
# BAIDU_SECRET_KEY=your-baidu-secret-key
# STEP_API_KEY=your-step-api-key
# MINIMAX_API_KEY=your-minimax-api-key
# AZURE_API_KEY=your-azure-api-key
# GOOGLE_API_KEY=your-google-api-key
