"""Add all entity models

Revision ID: 3fcb3159212b
Revises: 5e42ba3361a9
Create Date: 2025-10-03 13:25:56.570511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcb3159212b'
down_revision: Union[str, Sequence[str], None] = '5e42ba3361a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='模型类型'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft, training, trained, deployed, archived'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='模型文件路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节）'),
    sa.Column('accuracy', sa.Float(), nullable=True, comment='准确率'),
    sa.Column('precision', sa.Float(), nullable=True, comment='精确率'),
    sa.Column('recall', sa.Float(), nullable=True, comment='召回率'),
    sa.Column('f1_score', sa.Float(), nullable=True, comment='F1分数'),
    sa.Column('training_data_size', sa.Integer(), nullable=True, comment='训练数据大小'),
    sa.Column('training_time', sa.Integer(), nullable=True, comment='训练时间（秒）'),
    sa.Column('hyperparameters', sa.JSON(), nullable=True, comment='超参数'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='评估指标'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文章标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('excerpt', sa.Text(), nullable=True, comment='文章摘要'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft, published, archived'),
    sa.Column('featured_image', sa.String(length=500), nullable=True, comment='特色图片'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签，逗号分隔'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='浏览量'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='文章ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父评论ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending, approved, rejected'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
